---
name: Caddy 2
version: 2.0.3.1dev5
slug: caddy-2
description: Open source web and proxy server with automatic HTTPS
url: "https://github.com/seb5594/Home-Assistant-Addon-Caddy-2"
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
startup: services
map:
  - type: share
    read_only: false
  - type: addon_config
    read_only: false
  - type: ssl
    read_only: false
host_network: true
options:
  non_caddyfile_config:
    email: your@email.com
    domain: mydomain.com
    destination: localhost
    port: 8123
  args: []
  env_vars: []
  log_level: info
  mount_files: []
schema:
  non_caddyfile_config:
    email: email?
    domain: str?
    destination: str?
    port: port?
  caddy_upgrade: bool?
  caddy_fmt: bool?
  args:
    - str
  env_vars:
    - name: str
      value: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  mount_files:
    - str
environment:
  LOG_FORMAT: "{LEVEL}: {MESSAGE}"
init: false
breaking_versions:
  - 2.0.0
